"""Bake in-place Walk and Run clips into the open Lancer rig (also via MCP).

Preserves the mesh, rest skeleton, and authored Idle. Foot placement is solved
analytically, then stored as ordinary bone keys; no runtime IK is required.
"""
from pathlib import Path
import json
import math

import bpy
from mathutils import Matrix, Vector

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
OUT = ROOT / "apps/web/public/models/hollow-legion"
TAG = "stakewars_lancer_locomotion_v1"
FPS = 24
GROUND = .006
GAITS = {
    "Walk": dict(period=32, duty=.60, stride=.56, lift=.115,
                 drop=.075, bob=.020, lean=.045, yaw=.030,
                 arm=.28, cannon_arm=.10, elbow=.25, cannon_elbow=.25),
    "Run": dict(period=16, duty=.40, stride=.72, lift=.245,
                drop=.175, bob=.035, lean=.160, yaw=.055,
                arm=.60, cannon_arm=.19, elbow=.90, cannon_elbow=.85),
}

scene = bpy.data.scenes["LANCER | Studio"]
rig = bpy.data.objects["Lancer"]
mesh = bpy.data.objects["Lancer_Armor"]
assert rig.type == "ARMATURE" and len(rig.data.bones) == 17
if bpy.context.screen and bpy.context.screen.is_animation_playing:
    bpy.ops.screen.animation_cancel(restore_frame=False)
if bpy.context.object and bpy.context.object.mode != "OBJECT":
    bpy.ops.object.mode_set(mode="OBJECT")
bpy.context.window.scene = scene
scene.render.fps = FPS
rig.data.pose_position = "POSE"
rig.animation_data_create()
if rig.animation_data.action:
    active = rig.animation_data.action
    assert active.get("generator") == TAG, "Preserve the active action before baking locomotion"
    rig.animation_data.action = None
    bpy.data.actions.remove(active)
for track in list(rig.animation_data.nla_tracks):
    if track.name in GAITS:
        assert all(s.action.get("generator") == TAG for s in track.strips), "Existing locomotion is not generated by this script"
        actions = [s.action for s in track.strips]
        rig.animation_data.nla_tracks.remove(track)
        for action in actions:
            if action.users <= 1:
                bpy.data.actions.remove(action)
    else:
        track.mute = True

rest = {b.name: b.matrix_local.copy() for b in rig.data.bones}
rest_inverse = {name: matrix.inverted() for name, matrix in rest.items()}
legs = {}
for side in ("R", "L"):
    upper, lower, foot = [rig.data.bones[side + suffix] for suffix in (".UpperLeg", ".LowerLeg", ".Foot")]
    group = mesh.vertex_groups[foot.name].index
    offsets = [v.co - foot.head_local for v in mesh.data.vertices
               if any(g.group == group and g.weight > .99 for g in v.groups)]
    legs[side] = dict(hip=upper.head_local.copy(), knee=lower.head_local.copy(),
                      ankle=foot.head_local.copy(), offsets=offsets,
                      length1=upper.length, length2=lower.length)


def pivot_rotation(pivot, rotation):
    return Matrix.Translation(pivot) @ rotation @ Matrix.Translation(-pivot)


def joint(name, rotation, poses):
    parent = rig.data.bones[name].parent.name
    inherited = poses[parent] @ rest_inverse[parent]
    return inherited @ pivot_rotation(rig.data.bones[name].head_local, rotation) @ rest[name]


def aimed(name, head, tail):
    bone = rig.data.bones[name]
    rotation = (bone.tail_local - bone.head_local).rotation_difference(tail - head)
    matrix = rotation.to_matrix().to_4x4() @ rest[name]
    matrix.translation = head
    return matrix


def foot_path(phase, gait):
    stride, duty = gait["stride"], gait["duty"]
    if phase <= duty:
        return stride * (phase / duty - .5), 0.0, 0.0
    u = (phase - duty) / (1 - duty)
    smooth = u * u * (3 - 2 * u)
    # Hermite tangents match stance speed at toe-off and landing.
    tangent = stride * (1 - duty) / duty
    y = stride * (.5 - smooth) + tangent * (2 * u**3 - 3 * u*u + u)
    lift = gait["lift"] * math.sin(math.pi * u)**2
    pitch = -(.18 if gait["period"] == 32 else .35) * math.sin(math.pi * u)
    return y, lift, pitch


def pose_at(phase, gait):
    running = gait["period"] == 16
    cycle = math.tau * phase
    yaw = gait["yaw"] * math.sin(cycle)
    high_phase = .45 if running else .30
    offset = Vector((-.014 * math.sin(cycle), -.035 if running else 0,
                     -gait["drop"] + gait["bob"] * math.cos(2 * math.tau * (phase - high_phase))))
    hips_deformation = Matrix.Translation(offset) @ pivot_rotation(
        rig.data.bones["Hips"].head_local, Matrix.Rotation(yaw, 4, "Z"))
    poses = {"Root": rest["Root"].copy(), "Hips": hips_deformation @ rest["Hips"]}
    lean = gait["lean"] + .010 * math.sin(2 * cycle)
    poses["Spine"] = joint("Spine", Matrix.Rotation(lean, 4, "X") @ Matrix.Rotation(-1.6 * yaw, 4, "Z"), poses)
    poses["Head"] = joint("Head", Matrix.Rotation(-lean * .45, 4, "X"), poses)
    for side, sign in (("R", 1), ("L", -1)):
        amplitude = gait["cannon_arm"] if side == "R" else gait["arm"]
        swing = sign * amplitude * math.cos(cycle)
        splay = sign * (.14 if running else .09)
        poses[side + ".UpperArm"] = joint(side + ".UpperArm",
            Matrix.Rotation(swing, 4, "X") @ Matrix.Rotation(splay, 4, "Y"), poses)
        elbow = gait["cannon_elbow"] if side == "R" else gait["elbow"]
        poses[side + ".Forearm"] = joint(side + ".Forearm", Matrix.Rotation(-elbow, 4, "X"), poses)
    poses["L.Hand"] = joint("L.Hand", Matrix.Identity(4), poses)
    poses["Cannon"] = joint("Cannon", Matrix.Identity(4), poses)
    poses["Muzzle"] = joint("Muzzle", Matrix.Identity(4), poses)
    for side, leg in legs.items():
        p = (phase + (0 if side == "R" else .5)) % 1
        y, lift, pitch = foot_path(p, gait)
        foot_rotation = Matrix.Rotation(pitch, 4, "X")
        ankle = leg["ankle"].copy()
        ankle.y += y
        ankle.z = GROUND + lift - min((foot_rotation @ v).z for v in leg["offsets"])
        hip = hips_deformation @ leg["hip"]
        delta = ankle - hip
        distance = delta.length
        a, b = leg["length1"], leg["length2"]
        assert abs(a - b) + .001 < distance < a + b - .001, (side, phase, distance, a + b)
        direction = delta.normalized()
        pole = Vector((0, -1, 0))
        bend = (pole - direction * pole.dot(direction)).normalized()
        along = (a*a - b*b + distance*distance) / (2 * distance)
        knee = hip + direction * along + bend * math.sqrt(max(0, a*a - along*along))
        poses[side + ".UpperLeg"] = aimed(side + ".UpperLeg", hip, knee)
        poses[side + ".LowerLeg"] = aimed(side + ".LowerLeg", knee, ankle)
        foot_matrix = foot_rotation @ rest[side + ".Foot"]
        foot_matrix.translation = ankle
        poses[side + ".Foot"] = foot_matrix
    for pose in rig.pose.bones:
        pose.rotation_mode = "XYZ"  # Idle uses Euler curves; preserve its playback.
        kwargs = {}
        if pose.parent:
            kwargs = dict(parent_matrix=poses[pose.parent.name], parent_matrix_local=rest[pose.parent.name])
        pose.matrix_basis = pose.bone.convert_local_to_pose(
            poses[pose.name], rest[pose.name], invert=True, **kwargs)


for gait in GAITS.values():
    for sample in range(gait["period"] * 4):
        pose_at(sample / (gait["period"] * 4), gait)

for name, gait in GAITS.items():
    period = gait["period"]
    for frame in range(period + 1):
        scene.frame_set(frame)
        pose_at((frame % period) / period, gait)
        for pose in rig.pose.bones:
            for prop in ("location", "rotation_euler", "scale"):
                pose.keyframe_insert(prop, frame=frame, group=pose.name)
        rig.animation_data.action["generator"] = TAG
    action = rig.animation_data.action
    action.name = name
    action["generator"] = TAG
    action.use_fake_user = True
    for layer in action.layers:
        for strip in layer.strips:
            for bag in strip.channelbags:
                for curve in bag.fcurves:
                    for key in curve.keyframe_points:
                        key.interpolation = "LINEAR"
    track = rig.animation_data.nla_tracks.new()
    track.name = name
    track.strips.new(name, 0, action)
    track.mute = True
    rig.animation_data.action = None
    rig[name.lower() + "_duration_seconds"] = period / FPS
    rig[name.lower() + "_speed_mps"] = gait["stride"] / (gait["duty"] * period / FPS)
rig["locomotion_notes"] = "In-place +Z-forward glTF clips; scale actor translation and clip rate together. No runtime IK."

# Export all NLA clips, with the unchanged rest mesh as the default glTF pose.
for pose in rig.pose.bones:
    pose.matrix_basis = Matrix.Identity(4)
scene.frame_set(0)
bpy.context.view_layer.update()
bpy.ops.object.select_all(action="DESELECT")
rig.select_set(True)
mesh.select_set(True)
bpy.context.view_layer.objects.active = mesh
OUT.mkdir(parents=True, exist_ok=True)
bpy.ops.export_scene.gltf(filepath=str(OUT / "lancer.glb"), export_format="GLB", use_selection=True,
    use_active_scene=True, export_apply=True, export_animations=True, export_frame_range=False,
    export_animation_mode="NLA_TRACKS", export_nla_strips=True, export_skins=True,
    export_yup=True, export_extras=True, export_cameras=False, export_lights=False)

for track in rig.animation_data.nla_tracks:
    track.mute = track.name != "Walk"
scene.frame_start, scene.frame_end = 0, GAITS["Walk"]["period"] - 1
scene.frame_set(0)
scene.render.filepath = "//lancer-preview.png"
bpy.ops.object.select_all(action="DESELECT")
rig.select_set(True)
bpy.context.view_layer.objects.active = rig
bpy.context.preferences.filepaths.save_version = 0
bpy.ops.wm.save_as_mainfile(filepath=str(HERE / "lancer.blend"))

stats_path = HERE / "asset-stats.json"
stats = json.loads(stats_path.read_text()) if stats_path.exists() else {}
stats.update(animations=["Idle", "Walk", "Run"], rigged_bytes=(OUT / "lancer.glb").stat().st_size,
             locomotion={name: dict(duration_seconds=gait["period"] / FPS,
                 speed_mps=rig[name.lower() + "_speed_mps"], stance_fraction=gait["duty"],
                 stride_m=gait["stride"], foot_lift_m=gait["lift"]) for name, gait in GAITS.items()})
stats_path.write_text(json.dumps(stats, indent=2) + "\n")
result = dict(blend=str(HERE / "lancer.blend"), clips=stats["animations"],
              locomotion=stats["locomotion"], rigged_bytes=stats["rigged_bytes"])
print(json.dumps(result, indent=2), flush=True)
