"""Bake in-place Walk and Run clips into the open Bulwark rig (also via MCP).

Preserves both meshes and the rest skeleton. Foot placement is solved
analytically, then stored as ordinary bone keys; no runtime IK is required.
"""
from pathlib import Path
import json
import math

import bpy
from mathutils import Matrix, Vector

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
OUT = ROOT / "apps/web/public/models/hollow-legion"
TAG = "stakewars_bulwark_locomotion_v1"
FPS = 24
GROUND = .006
GAITS = {
    "Walk": dict(period=40, duty=.64, stride=.40, lift=.09,
                 drop=.065, bob=.012, lean=.035, yaw=.018,
                 arm=.23, shield_arm=.025, elbow=.20, shield_elbow=.13),
    "Run": dict(period=24, duty=.38, stride=.50, lift=.17,
                drop=.13, bob=.025, lean=.105, yaw=.025,
                arm=.44, shield_arm=.045, elbow=.60, shield_elbow=.36),
}


scene = bpy.data.scenes["BULWARK | Studio"]
rig = bpy.data.objects["Bulwark"]
mesh = bpy.data.objects["Bulwark_Armor"]
shield = bpy.data.objects["Bulwark_Shield"]
assert rig.type == "ARMATURE" and len(rig.data.bones) == 18
if bpy.context.screen and bpy.context.screen.is_animation_playing:
    bpy.ops.screen.animation_cancel(restore_frame=False)
if bpy.context.object and bpy.context.object.mode != "OBJECT":
    bpy.ops.object.mode_set(mode="OBJECT")
bpy.context.window.scene = scene
scene.render.fps = FPS
rig.data.pose_position = "POSE"
rig.animation_data_create()
if rig.animation_data.action:
    active = rig.animation_data.action
    assert active.get("generator") == TAG, "Preserve the active action before baking locomotion"
    rig.animation_data.action = None
    bpy.data.actions.remove(active)
for track in list(rig.animation_data.nla_tracks):
    if track.name in GAITS:
        assert all(s.action.get("generator") == TAG for s in track.strips), "Existing locomotion is not generated by this script"
        actions = [s.action for s in track.strips]
        rig.animation_data.nla_tracks.remove(track)
        for action in actions:
            if action.users <= 1:
                bpy.data.actions.remove(action)
    else:
        track.mute = True

rest = {b.name: b.matrix_local.copy() for b in rig.data.bones}
rest_inverse = {name: matrix.inverted() for name, matrix in rest.items()}
legs = {}
for side in ("R", "L"):
    upper, lower, foot = [rig.data.bones[side + suffix] for suffix in (".UpperLeg", ".LowerLeg", ".Foot")]
    group = mesh.vertex_groups[foot.name].index
    offsets = [v.co - foot.head_local for v in mesh.data.vertices
               if any(g.group == group and g.weight > .99 for g in v.groups)]
    legs[side] = dict(hip=upper.head_local.copy(), knee=lower.head_local.copy(),
                      ankle=foot.head_local.copy(), offsets=offsets,
                      length1=upper.length, length2=lower.length)


def pivot_rotation(pivot, rotation):
    return Matrix.Translation(pivot) @ rotation @ Matrix.Translation(-pivot)


def joint(name, rotation, poses):
    parent = rig.data.bones[name].parent.name
    inherited = poses[parent] @ rest_inverse[parent]
    return inherited @ pivot_rotation(rig.data.bones[name].head_local, rotation) @ rest[name]


def aimed(name, head, tail):
    bone = rig.data.bones[name]
    rotation = (bone.tail_local - bone.head_local).rotation_difference(tail - head)
    matrix = rotation.to_matrix().to_4x4() @ rest[name]
    matrix.translation = head
    return matrix


def foot_path(phase, gait):
    stride, duty = gait["stride"], gait["duty"]
    if phase <= duty:
        return stride * (phase / duty - .5), 0.0, 0.0
    u = (phase - duty) / (1 - duty)
    smooth = u * u * (3 - 2 * u)
    # Hermite tangents match stance speed at toe-off and landing.
    tangent = stride * (1 - duty) / duty
    y = stride * (.5 - smooth) + tangent * (2 * u**3 - 3 * u*u + u)
    lift = gait["lift"] * math.sin(math.pi * u)**2
    pitch = -(.12 if gait["period"] == 40 else .24) * math.sin(math.pi * u)
    return y, lift, pitch


def pose_at(phase, gait):
    running = gait["period"] == 24
    cycle = math.tau * phase
    yaw = gait["yaw"] * math.sin(cycle)
    high_phase = .45 if running else .30
    offset = Vector((-.012 * math.sin(cycle), -.025 if running else 0,
                     -gait["drop"] + gait["bob"] * math.cos(2 * math.tau * (phase - high_phase))))
    hips_deformation = Matrix.Translation(offset) @ pivot_rotation(
        rig.data.bones["Hips"].head_local, Matrix.Rotation(yaw, 4, "Z"))
    poses = {"Root": rest["Root"].copy(), "Hips": hips_deformation @ rest["Hips"]}
    lean = gait["lean"] + .010 * math.sin(2 * cycle)
    poses["Spine"] = joint("Spine", Matrix.Rotation(lean, 4, "X") @ Matrix.Rotation(-1.6 * yaw, 4, "Z"), poses)
    poses["Head"] = joint("Head", Matrix.Rotation(-lean * .45, 4, "X"), poses)
    for side, sign in (("R", 1), ("L", -1)):
        sx = -sign
        amplitude = gait["shield_arm"] if side == "L" else gait["arm"]
        swing = sign * amplitude * math.cos(cycle)
        # The rest rig is T-shaped. First lower the arms, then add world-space swing.
        base = Vector((sx, 0, 0)).rotation_difference(Vector((sx * .30, -.08, -.95)).normalized()).to_matrix().to_4x4()
        poses[side + ".UpperArm"] = joint(side + ".UpperArm",
            Matrix.Rotation(swing, 4, "X") @ base, poses)
        elbow = gait["shield_elbow"] if side == "L" else gait["elbow"]
        # Joint() inherits the upper arm transform; conjugate a world-X bend into
        # the rest arm's frame so the forearm bends forward rather than sideways.
        bend = base.inverted() @ Matrix.Rotation(-elbow, 4, "X") @ base
        poses[side + ".Forearm"] = joint(side + ".Forearm", bend, poses)
        poses[side + ".Hand"] = joint(side + ".Hand", Matrix.Identity(4), poses)
        poses[side + ".EquipmentSocket"] = joint(side + ".EquipmentSocket", Matrix.Identity(4), poses)
    # Carry the shield across the left half of the chest with a bent elbow.
    # Solve the arm to the grip; keep the shield rigid and its broad face forward.
    shoulder = poses["Spine"] @ rest_inverse["Spine"] @ rig.data.bones["L.UpperArm"].head_local
    wrist = Vector((.32 + offset.x, -.35 - (.035 if running else 0) + .012 * math.cos(cycle),
                    1.00 + gait["bob"] * math.cos(2 * cycle)))
    delta = wrist - shoulder
    distance = delta.length
    a, b = rig.data.bones["L.UpperArm"].length, rig.data.bones["L.Forearm"].length
    assert abs(a-b)+.001 < distance < a+b-.001, ("shield arm", phase, distance)
    direction = delta.normalized()
    pole = Vector((1, 0, .1))
    bend = (pole - direction * pole.dot(direction)).normalized()
    along = (a*a-b*b+distance*distance)/(2*distance)
    elbow = shoulder + direction*along + bend*math.sqrt(max(0, a*a-along*along))
    poses["L.UpperArm"] = aimed("L.UpperArm", shoulder, elbow)
    poses["L.Forearm"] = aimed("L.Forearm", elbow, wrist)
    hand_base = Vector((1,0,0)).rotation_difference(Vector((.30,-.08,-.95)).normalized()).to_matrix().to_4x4()
    poses["L.Hand"] = hand_base @ rest["L.Hand"]
    poses["L.Hand"].translation = wrist
    poses["L.EquipmentSocket"] = joint("L.EquipmentSocket", Matrix.Identity(4), poses)
    for side, leg in legs.items():
        p = (phase + (0 if side == "R" else .5)) % 1
        y, lift, pitch = foot_path(p, gait)
        foot_rotation = Matrix.Rotation(pitch, 4, "X")
        ankle = leg["ankle"].copy()
        ankle.y += y
        ankle.z = GROUND + lift - min((foot_rotation @ v).z for v in leg["offsets"])
        hip = hips_deformation @ leg["hip"]
        delta = ankle - hip
        distance = delta.length
        a, b = leg["length1"], leg["length2"]
        assert abs(a - b) + .001 < distance < a + b - .001, (side, phase, distance, a + b)
        direction = delta.normalized()
        pole = Vector((0, -1, 0))
        bend = (pole - direction * pole.dot(direction)).normalized()
        along = (a*a - b*b + distance*distance) / (2 * distance)
        knee = hip + direction * along + bend * math.sqrt(max(0, a*a - along*along))
        poses[side + ".UpperLeg"] = aimed(side + ".UpperLeg", hip, knee)
        poses[side + ".LowerLeg"] = aimed(side + ".LowerLeg", knee, ankle)
        foot_matrix = foot_rotation @ rest[side + ".Foot"]
        foot_matrix.translation = ankle
        poses[side + ".Foot"] = foot_matrix
    for pose in rig.pose.bones:
        pose.rotation_mode = "QUATERNION"
        kwargs = {}
        if pose.parent:
            kwargs = dict(parent_matrix=poses[pose.parent.name], parent_matrix_local=rest[pose.parent.name])
        pose.matrix_basis = pose.bone.convert_local_to_pose(
            poses[pose.name], rest[pose.name], invert=True, **kwargs)


for gait in GAITS.values():
    for sample in range(gait["period"] * 4):
        pose_at(sample / (gait["period"] * 4), gait)

for name, gait in GAITS.items():
    period = gait["period"]
    for frame in range(period + 1):
        scene.frame_set(frame)
        pose_at((frame % period) / period, gait)
        for pose in rig.pose.bones:
            for prop in ("location", "rotation_quaternion", "scale"):
                pose.keyframe_insert(prop, frame=frame, group=pose.name)
        rig.animation_data.action["generator"] = TAG
    action = rig.animation_data.action
    action.name = name
    action["generator"] = TAG
    action.use_fake_user = True
    for layer in action.layers:
        for strip in layer.strips:
            for bag in strip.channelbags:
                for curve in bag.fcurves:
                    for key in curve.keyframe_points:
                        key.interpolation = "LINEAR"
    track = rig.animation_data.nla_tracks.new()
    track.name = name
    track.strips.new(name, 0, action)
    track.mute = True
    rig.animation_data.action = None
    rig[name.lower() + "_duration_seconds"] = period / FPS
    rig[name.lower() + "_speed_mps"] = gait["stride"] / (gait["duty"] * period / FPS)
rig["locomotion_notes"] = "In-place +Z-forward glTF clips; scale actor translation and clip rate together. No runtime IK."

# Export all NLA clips, with the unchanged rest meshes as the default glTF pose.
for pose in rig.pose.bones:
    pose.matrix_basis = Matrix.Identity(4)
scene.frame_set(0)
bpy.context.view_layer.update()
bpy.ops.object.select_all(action="DESELECT")
rig.select_set(True)
mesh.select_set(True)
shield.select_set(True)
bpy.context.view_layer.objects.active = mesh
OUT.mkdir(parents=True, exist_ok=True)
bpy.ops.export_scene.gltf(filepath=str(OUT / "bulwark.glb"), export_format="GLB", use_selection=True,
    use_active_scene=True, export_apply=True, export_animations=True, export_frame_range=False,
    export_animation_mode="NLA_TRACKS", export_nla_strips=True, export_skins=True,
    export_yup=True, export_extras=True, export_cameras=False, export_lights=False)

for track in rig.animation_data.nla_tracks:
    track.mute = track.name != "Walk"
scene.frame_start, scene.frame_end = 0, GAITS["Walk"]["period"] - 1
scene.frame_set(0)
scene.render.filepath = "//bulwark-preview.png"
bpy.ops.object.select_all(action="DESELECT")
rig.select_set(True)
bpy.context.view_layer.objects.active = rig
bpy.context.preferences.filepaths.save_version = 0
bpy.ops.wm.save_as_mainfile(filepath=str(HERE / "bulwark.blend"))

stats_path = HERE / "asset-stats.json"
stats = json.loads(stats_path.read_text()) if stats_path.exists() else {}
stats.update(animations=[track.name for track in rig.animation_data.nla_tracks], rigged_bytes=(OUT / "bulwark.glb").stat().st_size,
             locomotion={name: dict(duration_seconds=gait["period"] / FPS,
                 speed_mps=rig[name.lower() + "_speed_mps"], stance_fraction=gait["duty"],
                 stride_m=gait["stride"], foot_lift_m=gait["lift"]) for name, gait in GAITS.items()})
stats_path.write_text(json.dumps(stats, indent=2) + "\n")
result = dict(blend=str(HERE / "bulwark.blend"), clips=stats["animations"],
              locomotion=stats["locomotion"], rigged_bytes=stats["rigged_bytes"])
print(json.dumps(result, indent=2), flush=True)
