[sql]
historical = [
  "stakewars-ControlPoint",
  "stakewars-OperatorState",
  "stakewars-ControlPointCaptured",
  "stakewars-ControlPointDisplaced",
  "stakewars-ControlPointReinforced",
  "stakewars-ControlPointReleased",
  "stakewars-ControlPointRedeployed",
  "stakewars-OperatorDisqualified",
]
